#ifndef __CHEBY__RXPI_GTHE4_MAP__H__
#define __CHEBY__RXPI_GTHE4_MAP__H__

#define RXPI_GTHE4_MAP_SIZE 44 /* 0x2c */

/* magic number to check presence */
#define RXPI_GTHE4_MAP_ID 0x0UL
#define RXPI_GTHE4_MAP_ID_PRESET 0x618e4UL

/* Reset register */
#define RXPI_GTHE4_MAP_RESET 0x4UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_PMA_RST 0x1UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_PMA_RST_MASK 0x1UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_PMA_RST_SHIFT 0
#define RXPI_GTHE4_MAP_RESET_GTH_RST 0x2UL
#define RXPI_GTHE4_MAP_RESET_GTH_RST_MASK 0x2UL
#define RXPI_GTHE4_MAP_RESET_GTH_RST_SHIFT 1
#define RXPI_GTHE4_MAP_RESET_GTH_TX_RST 0x4UL
#define RXPI_GTHE4_MAP_RESET_GTH_TX_RST_MASK 0x4UL
#define RXPI_GTHE4_MAP_RESET_GTH_TX_RST_SHIFT 2
#define RXPI_GTHE4_MAP_RESET_GTH_TX_PCS_RST 0x8UL
#define RXPI_GTHE4_MAP_RESET_GTH_TX_PCS_RST_MASK 0x8UL
#define RXPI_GTHE4_MAP_RESET_GTH_TX_PCS_RST_SHIFT 3
#define RXPI_GTHE4_MAP_RESET_GTH_TX_PMA_RST 0x10UL
#define RXPI_GTHE4_MAP_RESET_GTH_TX_PMA_RST_MASK 0x10UL
#define RXPI_GTHE4_MAP_RESET_GTH_TX_PMA_RST_SHIFT 4
#define RXPI_GTHE4_MAP_RESET_GTH_RX_RST 0x20UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_RST_MASK 0x20UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_RST_SHIFT 5
#define RXPI_GTHE4_MAP_RESET_GTH_RX_PCS_RST 0x40UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_PCS_RST_MASK 0x40UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_PCS_RST_SHIFT 6
#define RXPI_GTHE4_MAP_RESET_GTH_RX_BUF_RST 0x80UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_BUF_RST_MASK 0x80UL
#define RXPI_GTHE4_MAP_RESET_GTH_RX_BUF_RST_SHIFT 7
#define RXPI_GTHE4_MAP_RESET_RXPI_RST 0x10000UL
#define RXPI_GTHE4_MAP_RESET_RXPI_RST_MASK 0x10000UL
#define RXPI_GTHE4_MAP_RESET_RXPI_RST_SHIFT 16

/* REG status */
#define RXPI_GTHE4_MAP_STATUS 0x8UL
#define RXPI_GTHE4_MAP_STATUS_PHY_READY 0x1UL
#define RXPI_GTHE4_MAP_STATUS_PHY_READY_MASK 0x1UL
#define RXPI_GTHE4_MAP_STATUS_PHY_READY_SHIFT 0
#define RXPI_GTHE4_MAP_STATUS_EXTRA_MASK 0xffff0000UL
#define RXPI_GTHE4_MAP_STATUS_EXTRA_SHIFT 16

/* REG ctrl */
#define RXPI_GTHE4_MAP_CTRL 0xcUL
#define RXPI_GTHE4_MAP_CTRL_RDY 0x1UL
#define RXPI_GTHE4_MAP_CTRL_RDY_MASK 0x1UL
#define RXPI_GTHE4_MAP_CTRL_RDY_SHIFT 0

/* Bitslide */
#define RXPI_GTHE4_MAP_BITSLIDE 0x10UL

/* REG rxpi_nsamp */
#define RXPI_GTHE4_MAP_RXPI_NSAMP 0x14UL

/* REG rxpi_shift */
#define RXPI_GTHE4_MAP_RXPI_SHIFT 0x18UL

/* Control for phase shift */
#define RXPI_GTHE4_MAP_PS_CTRL 0x1cUL
#define RXPI_GTHE4_MAP_PS_CTRL_RST 0x1UL
#define RXPI_GTHE4_MAP_PS_CTRL_RST_MASK 0x1UL
#define RXPI_GTHE4_MAP_PS_CTRL_RST_SHIFT 0
#define RXPI_GTHE4_MAP_PS_CTRL_PD 0x2UL
#define RXPI_GTHE4_MAP_PS_CTRL_PD_MASK 0x2UL
#define RXPI_GTHE4_MAP_PS_CTRL_PD_SHIFT 1
#define RXPI_GTHE4_MAP_PS_CTRL_INCDEC 0x100UL
#define RXPI_GTHE4_MAP_PS_CTRL_INCDEC_MASK 0x100UL
#define RXPI_GTHE4_MAP_PS_CTRL_INCDEC_SHIFT 8
#define RXPI_GTHE4_MAP_PS_CTRL_SHIFT 0x200UL
#define RXPI_GTHE4_MAP_PS_CTRL_SHIFT_MASK 0x200UL
#define RXPI_GTHE4_MAP_PS_CTRL_SHIFT_SHIFT 9

/* Status for phase shift */
#define RXPI_GTHE4_MAP_PS_STAT 0x20UL
#define RXPI_GTHE4_MAP_PS_STAT_PHASE_MASK 0xffffUL
#define RXPI_GTHE4_MAP_PS_STAT_PHASE_SHIFT 0
#define RXPI_GTHE4_MAP_PS_STAT_FB_STOPPED 0x10000UL
#define RXPI_GTHE4_MAP_PS_STAT_FB_STOPPED_MASK 0x10000UL
#define RXPI_GTHE4_MAP_PS_STAT_FB_STOPPED_SHIFT 16
#define RXPI_GTHE4_MAP_PS_STAT_IN_STOPPED 0x20000UL
#define RXPI_GTHE4_MAP_PS_STAT_IN_STOPPED_MASK 0x20000UL
#define RXPI_GTHE4_MAP_PS_STAT_IN_STOPPED_SHIFT 17
#define RXPI_GTHE4_MAP_PS_STAT_LOCKED 0x40000UL
#define RXPI_GTHE4_MAP_PS_STAT_LOCKED_MASK 0x40000UL
#define RXPI_GTHE4_MAP_PS_STAT_LOCKED_SHIFT 18
#define RXPI_GTHE4_MAP_PS_STAT_PS_BUSY 0x80000UL
#define RXPI_GTHE4_MAP_PS_STAT_PS_BUSY_MASK 0x80000UL
#define RXPI_GTHE4_MAP_PS_STAT_PS_BUSY_SHIFT 19

/* Number of sampling for ps */
#define RXPI_GTHE4_MAP_PS_COUNT 0x24UL
#define RXPI_GTHE4_MAP_PS_COUNT_VAL_MASK 0xffffffUL
#define RXPI_GTHE4_MAP_PS_COUNT_VAL_SHIFT 0

/* Number of sampling for ps */
#define RXPI_GTHE4_MAP_PS_RES 0x28UL
#define RXPI_GTHE4_MAP_PS_RES_VAL_MASK 0xffffffUL
#define RXPI_GTHE4_MAP_PS_RES_VAL_SHIFT 0
#define RXPI_GTHE4_MAP_PS_RES_GEN_MASK 0xff000000UL
#define RXPI_GTHE4_MAP_PS_RES_GEN_SHIFT 24

#ifndef __ASSEMBLER__
struct rxpi_gthe4_map {
  /* [0x0]: REG (ro) magic number to check presence */
  uint32_t id;

  /* [0x4]: REG (rw) Reset register */
  uint32_t reset;

  /* [0x8]: REG (ro) */
  uint32_t status;

  /* [0xc]: REG (rw) */
  uint32_t ctrl;

  /* [0x10]: REG (ro) Bitslide */
  uint32_t bitslide;

  /* [0x14]: REG (rw) */
  uint32_t rxpi_nsamp;

  /* [0x18]: REG (rw) */
  uint32_t rxpi_shift;

  /* [0x1c]: REG (rw) Control for phase shift */
  uint32_t ps_ctrl;

  /* [0x20]: REG (ro) Status for phase shift */
  uint32_t ps_stat;

  /* [0x24]: REG (wo) Number of sampling for ps */
  uint32_t ps_count;

  /* [0x28]: REG (ro) Number of sampling for ps */
  uint32_t ps_res;
};
#endif /* !__ASSEMBLER__*/

#endif /* __CHEBY__RXPI_GTHE4_MAP__H__ */
